language: scala
scala:
  - 2.11.11
script:
  - "sbt -batch clean evicted | tee sbt.log"
after_success:
#  - sbt coveralls
#  - bash <(curl -s https://codecov.io/bash)
  - grep -e "\* org.scala-lang" sbt.log
  - |
    n=`grep -ce "\* org.scala-lang" sbt.log`
    echo $n
    if [ "$n" -ne "0" ]; then echo "ERROR: Found conflicting dependencies inside biopet"; exit 1; fi
#    || \
#    (echo "ERROR: Found conflicting dependencies inside biopet" && exit 1)
  - "git diff --exit-code || (echo ERROR: Git changes detected, please regenerate the readme, create license headers and run scalafmt with: sbt biopetGenerateReadme headerCreate scalafmt && exit 1)"
